

name: CI Environment

on:
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo build!

      - name: Run a multi-line script
        if: github.event == 'push'
        run: |
          echo Add other actions to build
          
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: dev
      url: "https://www.youtube.com/watch?v=Oe-Yu3YP0YQ"
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo devolp 1!
      - name: Run a one-line script
        run: echo devolp 2!
 
  deploy-hmg:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: 
      name: hmg
      url: "https://www.youtube.com/channel/UCnQzZNPePG3EZMj7Qg3D0Sw"
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo homolog
              
