# This is a basic workflow to help you get started with Actions

name: CI Terraform

on:
  push:
    branches: [ terraform ]
  pull_request:
    branches: [ terraform ]
  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: |
          terraform init -backend-config="bucket=eks-tfstate-trinovati"  -backend-config="key=ci/terraform.tfstate" -backend-config="region=us-west-2" 
          terraform validate -no-color
          terraform fmt

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖${{ steps.validate.outputs.stdout }}
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`${process.env.PLAN}\`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    needs: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: tfsec
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Validate
        id: validate
        #if: github.ref == 'refs/heads/main'
        run: |
          terraform init -backend-config="bucket=eks-tfstate-trinovati"  -backend-config="key=ci/terraform.tfstate" -backend-config="region=us-west-2" 
          terraform validate -no-color
          terraform fmt
          terraform plan -out=config

      - name: Terraform Apply
        id: apply
        #if: github.ref == 'refs/heads/main'
        run: terraform apply config

      # - name: Terraform Destroy
      #   id: destroy
      #   #if: github.ref == 'refs/heads/main'
      #   run: terraform destroy -auto-approve
      
      - name: Create Release Issue
        uses: ./.github/actions/create-issue
        if: github.ref == 'refs/heads/main'
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            action-id: ${{ github.run_id }}
            package-version: ${{ env.package_version }}